### ISSUE TITLE
Commands: Rename Commands to Tasks

### ISSUE THREAD

**Issue by markbaaijens** [markbaaijens/rpmusicserver#105]
Commands is too technical, renaming this to Tasks is more friendly. Change this text and rename all (technical) objects like templates, etc.

**Comment by mimefly** [comment]
Should these 'commands' also be renamed to 'tasks'? 
e.g.  <a href="/commands/reboot-server">Reboot</a> and <a href="/commands/halt-server">Halt</a>

**Comment by markbaaijens** [comment]
Another /commands in the route for the actual command seems to be overdone. Just remove de /command from the route.
So:
@app.route('/commands/backup-server', methods=['GET'])
becomes
@app.route('/backup-server', methods=['GET'])
