### ISSUE TITLE
Bug: if backup-disk is not present, link to Backup should be disabled in web

### ISSUE THREAD

**Issue by markbaaijens** [markbaaijens/rpmusicserver#122]
Currenlty, the task BackupServer is always available, even if the backup-disk is not mounted. In that case, a user can still start the backup, even though you know in front that nothing will happen. In the backup-log is posted that there is no backup-disk present, so eventually nothing goes wrong. But is is better to disable the link and inform the user before hand.

## Steps to reproduce
* be sure no backup-disk is attached
* start the backup in the frontend/Task-page
* see that the process starts
* inspect the Backup-log for 'no backup-disk is present' (or something like that)

## To do
* extend API-call GetBackupInfo with new property IsBackupDiskPresent
  * use existing API-call GetDiskList/AppendDiskInfo
* disable link to BackupServer when backup-disk is not mounted
* show IsBackupDiskPresent = mount-status of backup-disk on Tasks-page: 
  * Indicator: checkmark when present, cross when not
  * Placement: right after link/button to BackupServer
  * Font: small
* show IsBackupInProgress
* Create a separate heading for Backup, right Server

See Update (on Tasks-page) for inspiration, This has the same (desired) mechanism.

**Comment by dartello** [comment]
The backup disk can be seen present in `ls /dev/disk/by-label` as well: `if "ls /dev/disk/by-label | grep usbbackup" == "usbbackup": ...`

**Comment by dartello** [comment]
I have a better idea that the indicator indicates whether RPMS can backup like CanUpdate. CanBackup depends on whether a disk is present and if so, that a backup is not already in progress.
