### ISSUE TITLE
Bug:  Swapping usbbackup to usbdata does not work as expected

### ISSUE THREAD

**Issue by markbaaijens** [markbaaijens/rpmusicserver#128]
Within RPMS, a backup consists of copying _all_ data from the usbdata- to the usbbackup-disk, so the backup-disk is a complete mirror of de data-disk. Then, it should be possible to swap them in the case the data-disk fails, just by renaming the label from usbbackup to usbdata
https://github.com/markbaaijens/rpmusicserver/blob/develop/README.md#disaster-recovery

## Steps to reproduce
* have a backup-disk in place on rpms
* do a backup
* power down the Pi
* rename label of backup-disk from usbbackup to usbdata
* unplug usbdata-disk
* power on Pi 
* see that no data is shown

Problem: swapping usbbackup to usbdata seems to works (web/disk-info shows a mounted disk) but no data is seen on /media/usbdata (by ssh). This is probably a rights issue. It should be investigated further.

Related: https://github.com/markbaaijens/rpmusicserver/issues/183

**Comment by markbaaijens** [comment]
Tested on a test-system/rpmsdev: it seems to work as intended, so it works flawlessly. First the rename of the backup-stick from usbbackup to usbdata: after a reboot al functions well, smb, transcoding, lms, etc. And then the original usbdata-stick from usbdata to usbbackup: a backup can be made without any trouble.

Maybe test in a (another) production system?

**Comment by mimefly** [comment]
Tested on development version of rpms (64bit).  Shutdown Pi, take out usbbackup, and rename it to usbdata.  Rebooting the Pi with the renamed usb drive; all seems to work well. 

Renamed old usbdata to usbbackup; seems to work oke.
