### ISSUE TITLE
If hostname or ip of rpms does not show up, mention to connect a display and keyboard to the pi (readme)

### ISSUE THREAD

**Issue by markbaaijens** [markbaaijens/rpmusicserver#134]
Normally, no keyboard or display is needed to install rpms to a Pi. But sometimes, when the Pi is not appearing to the network, some help in the form of a keyboard/display is needed to analyse the problem, This should be documented in the readme.

## Use case
As a user, I want to know what to do when the Pi does not appear in the network.

## Tasks (changes in Italic):
(1)
* if hostname `rpms` is not found (after reboot router):
  * reboot pi (best done by rpms web-interface)
* _if rpms still cannot be found, it's possible that the pi is unable to connect to the network:_
  * _connect a keyboard and display to the pi to troubleshoot the issue directly from the device_
  
(2)
* command `nmap 192.168.x.* -p 9002 --open` 
* must be  
* `nmap $(echo "$(hostname -I | cut -d"." -f1-3).*") -p 22 --open`

(3)
* find a device which has port 9002 open (that will be the Pi running RPMS)
* must be
* find a device which has port 22 open (that might be the Pi running RPMS)

(4)
* remove line:
  * fill for x your personal subnet-number; use hostname -I | awk '{print $1}' to retrieve that info

**Comment by DanielxBlack** [comment]
I can try to add the piece of documentation.

**Comment by DanielxBlack** [comment]
I am not sure if this is the correct format for commenting on the issue, but the final two lines would be the change proposed:

`## Troubleshooting
### *Pi/rpms cannot be reached on the network*
Sometimes the pi is not visible in the network, either by hostname `rpms` or even by ip-address.

* if rpms cannot be found, first try pinging for rpms:
  * `ping rpms`
* if there is no response from the ping-command, check if pi is running and properly connected to the network (watch network-leds on the pi)
* if there is no response from the ping-command, try:
  * `nmap 192.168.x.*`
  * fill for x your personal subnet-number; use `hostname -I` to retrieve that info
* try to ping by ip-address (if hostname `rpms` is not mentioned by nmap)
  * ping 192.168.x.y
* for most network-problems (no hostname shown for pi, multiple ip-addresses for hostname, not able to ping on hostname, etc.):
  * reboot router
* if hostname `rpms` is not found (after reboot router):
  * reboot pi (best done by rpms web-interface)
* if rpms still cannot be found, it's possible that the pi is unable to connect to the network:
  * connect a keyboard and display to the pi to troubleshoot the issue directly from the device`

**Comment by markbaaijens** [comment]
The addition looks good. 

As your question for contributing..... the 'normal' way in a long-term contribution-relationship is that I add you as contributor. Then you can branch off from the develop-branch, make your change and push this to github. Then you can make a pull request for that branch and after approval, this will be merged into develop. But.... if this is a one-off action, I'd rather prevent the hassle and I better pickup your change and process it myself. So it is up to you.....

**Comment by DanielxBlack** [comment]
> But.... if this is a one-off action, I'd rather prevent the hassle and I better pickup your change and process it myself. 

I think this would be the best solution as it's only that change. If I continue to contribute more, then perhaps we can go the contributor route.

**Comment by markbaaijens** [comment]
OK. Just browse the project and see if you can make more contributions if you like.

**Comment by dartello** [comment]
Aliasing is usually done by the router, which has an IP/Hostname table (database). All routes have this, but not all routes share this information to access a machine by hostname (DNS) even in DHCP.

**Comment by markbaaijens** [comment]
This comment has nothing to do with the problem encountered.... that the Pi is not visible in *any* way. In that case, a keyboard/display have to be connected to research the problem

**Comment by markbaaijens** [comment]
Is some duplication indeed. But in this case it is permitted.
