### ISSUE TITLE
Show OS-number and OS-type (32/64-bit)

### ISSUE THREAD

**Issue by markbaaijens** [markbaaijens/rpmusicserver#135]
Right now, only the codename of the OS is showed. What is desired is to show the OS-number and type (32/64-bit)

## Use case
As a user, I want _all_ available information of the used OS displayed in the front-end. So OS-number, -codename, further description and bit-type

## Tasks
* Implement two new variables in API-call GetMachineInfo:
  * OsDescription, use `lsb_release -a` => Description => Raspbian GNU/Linux 11 (bullseye)
  * OsBitType (bit-value), use `uname -m` => armv71 = 32, armv8 = 64
* Show OsDescription and OsBitType in front-end (home-page). 

## Note(s)
* Existing variable OsCodeName can be deleted from the front-end (b/c the codename is also displayed in the description), but must stay in the API for future usage.
* detecting OsBitType must also work in a non-arm environment

**Comment by dartello** [comment]
It is possible to just enter the OS-type as a specific OS will be downloaded in the burn process of the SD-card.
image=https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-11-08/2021-10-30-raspios-bullseye-armhf-lite.zip

**Comment by markbaaijens** [comment]
This is not very helpful. We have a OS in place onze downloaded, installed and booted. And with one command, we can see exactly what we want. It is not supposed to change the install-process, just to obtain the desired information. That would be counter-productive.

**Comment by dartello** [comment]
Can not test this as I have no test environment with a pi
