### ISSUE TITLE
Bug: Faster execution of service-detection

### ISSUE THREAD

**Issue by markbaaijens** [markbaaijens/rpmusicserver#138]
Service-detection by nmap takes 3s now, which is quite slow b/c for each port to be checked, a separate nmap-command is fired. 
Make this faster by executing the nmap-command once, store result and process the data.
Use the --open as parameter for nmap, so the pipe to "grep open" can be ommited (see below for explanation).

## Steps to reproduce
* open Services-page from the front-end
* see that is taking approximately 3 seconds (depending on hardware)

**Comment by markbaaijens** [comment]
"I'll try to investigate this one tonight if no one is able to look at it. The downside is that I don't have it installed for testing. I may need to pick up a Pi."
You can come pretty far by starting the API-controller and the Web-controller, then you can access the rpms web-interface from your local (development) machine. For this particular issue, that might be enough. In most cases, yes, you *must* have a physical Pi and install rpms on it. BTW, running rpms in a virtual machine is no solution, we experimented with that.

"There is a grep open. Nmap does have an arg called --open that would only output ports detected in "open" state."
Nice find. Possibly this is faster then the extra pipe to "grep open". But certainly better b/c it's a standard parameter. Let's take this (the usage of the nmap-parameter --open) as a starting point. I'll change the description of the issue for this.

**Comment by markbaaijens** [comment]
Do you wish to contribute in code?

**Comment by DanielxBlack** [comment]
I can make an attempt. I have some of the Nmap knowledge, but my Python understanding is a little bit lacking.

**Comment by DanielxBlack** [comment]
Thank you.

Apologies: Learning the GitHub workflow a little bit. 

To clarify: I created a new branch locally on my workstation from "Develop." Before making any changes, I make the PR and the "wait for author" tag puts it in something of a "hold"/"working" status that I can work from?

**Comment by markbaaijens** [comment]
_the "wait for author" tag puts it in something of a "hold"/"working" status_
That's correct, we only take a (close) look at the PR when the label is removed. It is also for administrative reasons, the binding of a PR to an issue. 

But to make the PR, you must first publish you branch, the you can mak the PR through the github website

**Comment by DanielxBlack** [comment]
Please forgive my limited capabilities with Python, I am looking at this section of code:

```
def AppendServiceInfo(portNumber, serviceName):
    # isActive => nmap localhost --open'
    isActive = False
    process = subprocess.run(["nmap localhost --open -p 22,80,139,445,5000,8384,9002,9090,9091"], stdout=subprocess.PIPE, shell=True)
    process = subprocess.run(["grep " + str(portNumber) + "/tcp"], input=process.stdout, stdout=subprocess.PIPE, shell=True)
    if process.stdout.decode("utf-8").strip('\n'):
        isActive = True

    services.append({
                    "PortNumber": portNumber,
                    "ServiceName": serviceName,
                    "IsActive": isActive
                 })
    pass
```

And I had two ideas. One seems straightforward and is shown above (hardcode the port numbers in the command)
as such:

` process = subprocess.run(["nmap localhost --open -p 22,80,139,445,5000,8384,9002,9090,9091"], stdout=subprocess.`


The other was to sort of "build" a string from the "GetServiceList" function:

```
def GetServiceList():
    services.clear()
    AppendServiceInfo(22, 'ssh')
    AppendServiceInfo(80, 'rpms/web')
    AppendServiceInfo(139, 'samba/netbios')
    AppendServiceInfo(445, 'samba/tcp')
    AppendServiceInfo(5000, 'rpms/api')
    AppendServiceInfo(8384, 'syncthing/web')
    AppendServiceInfo(9002, 'lms/web')
    AppendServiceInfo(9090, 'lms/telnet')
    AppendServiceInfo(9091, 'transmission/web')
    return services
```
But it's something I'm not quite sure how to do, and I don't know if it would be more beneficial one way or not.

Again, I apologize and hope to learn more as I go.

**Comment by markbaaijens** [comment]
Yikes, this is far more difficult than I initially thought, it's a chicken-and-egg problem: you want to execute the nmap once, but you do not know in front which ports to scan. Hardcoding the nmap-command is the easy way out, but is of course, a no go. 

_The other was to sort of "build" a string from the "GetServiceList" function:_
I guess this is the route we have to take, here in some psuedo-code:
* create an empty list ServiceList
* for each port, add an **object** of a class like PortInfo to the list (in stead of a json-tuple); that object has a property IsActive (among other properties like PortNumber and ServiceName); IsActive defaults to false
* If you are done populating this list, you can process this list and extract all port numbers (into a string or list)
* with that port-data, you know all the ports to be tested and can fire off a single nmap-command
* store the result in ResultList (which is essentially a list of open ports) 
* process the Services-list against ResultList, setting the IsActive-property for each port
* post-process Services-list to produce correct json-output

The essence is that you build a list with a bunch of objects (for each port one object) and than process that list later with the result of a single nmap command, configured by data (port numbers) from the list it self. For this to work, this data in the list must have some 'intelligence' thus cannot be a json-tuple but must be an (simple) object.

Does this make any sense?

**Comment by DanielxBlack** [comment]
> Yikes, this is far more difficult than I initially thought, it's a chicken-and-egg problem: you want to execute the nmap once, but you do not know in front which ports to scan. Hardcoding the nmap-command is the easy way out, but is of course, a no go.

I also noticed that the hard-code solution would very possibly cause issues with the chunk of code with "services.append" and definitely agree that hard-coding is the easy way out.


> Does this make any sense?

It does logically (i.e. I understand the idea). That said, to write it in code will be a new interesting challenge.

**Comment by markbaaijens** [comment]
You've made a start, in the right direction. I've made some comments in the PR. As this is a work-in-progress, these comments might be pre-mature.

**Comment by DanielxBlack** [comment]
Thank you. I will work off of your feedback today.

**Comment by DanielxBlack** [comment]
Note: I noticed that I will need to tighten up some spacing around lines 104-108.

I believe the new push might be a bit closer to the final goal: I create a "ServiceList" that remains empty. I create a "PortList" that lists attributes.

A for loop iterates through the ports to append 'PortNumber' to 'ServiceList'. Then 'ServiceList' is ultimately passed to a string embedded in the Nmap command. I think it may need a little work, and I want to ensure that the isActive becomes "True" as intended, but I feel like this may be on the right track.

**Comment by markbaaijens** [comment]
> I will admit that this is mostly piecing together the basics I know and a good lot of Google searches to understand what I am trying to accomplish, but I think that's how we all get there at some point.

Google is your friend, or better, stackoverflow is your friend ;)

At first, reading your notes in the previous message, I was thinking you were going in the good direction. But looking at your code, it is not (really). We are drifting further away from the goal = executing the nmap-command once and once only. Right now, the code isn't even compiling.....
(though some elements reflect the direction of the desired change)

There are just too many things 'wrong'. I can point them all out, but I guess you can figure it out your self by holding your code against the pseudo-code I have written above. 

A few pointers though (but not all):
* ServiceList and PortList should go *outside*  the class PortInfo (globals)
* Swap the names of ServiceList and PortList (rename ServiceList to PortList and PortList to ServiceList) so they reflect the usage
* class PortInfo should better be named ServiceInfo
* ServiceList should be a list of object of class ServiceInfo, inserted by the existing function AppendServiceInfo; thus the implementation of the function is completely changed

Once you have this in place, I think the rest of the implementation of the pseudo-code will be clear and easily implemented. 

Note. Using globals is not good practice. So eventually, I think these must go in a new class, as a singleton-implementation. But let's do this refactoring later, we must first see that we meet our goal, then we tidy up the code.

As I said, this issue is far more difficult then I anticipated, your 'struggling' made me aware of that. But eventually, we will succeed, don't worry. 

If it is not clear what I stated, your question are welcome. As always.

**Comment by DanielxBlack** [comment]
Thank you for the feedback. I will work on it some more tomorrow. I apologize as I know there are more advanced coders that could tackle this quickly. But thank you for all your help.

**Comment by DanielxBlack** [comment]
Due to a situation out of my control currently, I will likely be slow to respond in the meantime. I apologize for the inconvenience. I will continue to try when I can.

**Comment by markbaaijens** [comment]
It's OK. This issue is part of the new release v0.9 for which the kick-off has yet take place. For right now, we are not a hurry.

**Comment by markbaaijens** [comment]
As of now, we've started development on v0.9 in which this issue is a part. We are busy with some code in which it is essential that this issue must be solved.

Can you give us an update about your situation? If this is taking too long, we have to consider picking this issue ourselves.....

**Comment by markbaaijens** [comment]
OK, thank you for your reply, we'll take this issue under our care. Your welcome to contribute if your personal situation permits you to.
