### ISSUE TITLE
Multi-language: configuration

### ISSUE THREAD

**Issue by markbaaijens** [markbaaijens/rpmusicserver#144]
Right now, several labels are hardcoded in Dutch, such as the created path /media/usbdata/user/Publiek/Muziek. To be multilanguage, this setting must be configurable during install. The chosen language should be stored within rpms for (upcoming) updates.

## Use case
As a user, I want the names in the Samba-shares which are created by RPMS reflect my own language. Thus _Public_ and _Music_ in English and _Publiek_ and _Muziek_ in Dutch. If I want the labels to refect another language (say French), I should be able to change these labels.

## Currently hardcoded strings in Dutch
The only place where the language-specific labels appear, are through shares. Thus, the only thing what should happen is manipulating the samba-configuration.

* Share for 'Public': `/media/usbdata/user/public`
* Share for 'Music': `/media/usbdata/user/music`
* Share for 'Downloads': `/media/usbdata/user/downloads`  (implement as read-only)
* Share  for 'Backup': `/media/usbbackup/user`

## Implementation
* at burning: ask for language, Dutch = d English =e, German = g, French = f
  * create /etc/lang-choice.txt
  * contains d, e, g or f (depending on choice)
* at install-time: 
  * if /etc/lang-choice.txt exists 
  * if /media/usbdata/rpms/config/translations.json does NOT exist
    * generate a config-file /media/usbdata/rpms/config/translations.json 
      * PublicShareName
      * MusicShareName
      * BackupShareName
    * create in bash + jq
    * b/c translations.json is generated only once, we can later modify the values
    * rm /etc/lang-choice.txt
  * while generating smb.conf at install:
    * retrieve translations in translations.json for share-name and comment
    * read with jq
* web-interfaces
  * see transcode-settings for inspiration
  * api: implement calls
    * GetTranslations
    * SetPublicShareTranslation
    * SetMusicShareTranslation
    * SetBackupShareTranslation
  * web: implement UI to change labels
    * place on System-page
    * if saved:
      * write values to translations.json 
      * generate new samba-config
      * restart samba-server
    * path on Transcoder- and Music-page should resamble like this:
      * smb://[hostname]/[translated sharename], example: smb://rpms/Muziek
* change README.md
  * describe step on language in burn sd-card
* LMS
  * setting can be changed automatically at install by using an API-call to LMS to change the language
  * challenges
    * read from /etc/lang-choice.txt? which is removed after install
    * lms-server is not available at install-time
  * consideration(s):
    * change default language to English and demand a manual language-switch; so no automatic change

Example for translations.json
`{`
`    "PublicShareName": "Public",`
`    "MusicShareName": "Music",`
`    "DownloadsShareName": "Downloads",`
`    "BackupShareName": "Backup"`
`}`

## Note(s)
* the Dwonloads-share must be implemented as read-only

## Restrictions
* only 4 options given at burn-time to the user: Dutch/English/German/French
* language-switch is only applicable to (hardcoded) share-names, everything else (scripts, web-interface, etc.) stays the same, i.e. English

## Testing
* the update-proces must not override any language-specific setting
* trancoder, including editing settinge mus be tested to (api is hit)

**Comment by dartello** [comment]
Folders: Is it possible to give all folders lowercase names in English? For those who choose Dutch, get symbolic links to these "English" folders? Minimal configuration changes can be made in code and Docker containers.
Does this issue mean to also translate all documentation?

**Comment by markbaaijens** [comment]
"Folders: Is it possible to give all folders lowercase names in English?"
Possible yes, but we will not take that route (KISS). Our software is for normal users, not for developers with certain preferences

"Does this issue mean to also translate all documentation?"
As stated in the issue, documentation stays in English
