### ISSUE TITLE
Detect (from workstation) if local DNS is working, document in readme

### ISSUE THREAD

**Issue by markbaaijens** [markbaaijens/rpmusicserver#192]
In some local networks, local DNS does not work as supposed: a machine with a hostname cannot be resolved to a ip-address. This means that the machines cannot be addressed like that e.g.  `ping rpms` will not work. The origin of this problem is yet unknowm, but is described in our readme. Solution is to replace rpms with the actual ip-address when executing a command, see https://github.com/markbaaijens/rpmusicserver#pirpms-can-only-reached-by-ip-address

If the 'magical' command to detect a broken DNS, document this in te readme, prior to installing rpms.

## Use case
As a user installing rpms, I want to know in front, before installing rpms that my local DNS is not working, so I can antipate on that. Discovering the DNS-problem after booting the Pi is to late.

## Analysis
From the host, i.e. de rpms-pi, one can easily detect a broken DNS bij executing `nslookup rpms | grep "server can't find"`. The challenge is to have this information prior to installing/booting the Pi. Excuting `nslookup $(hostname)` from the desktop seems to work fine, which is actually a pity.

_What we our trying to find is the magical command a user can use to detect a broken DNS prior to installing rpms._

See also https://github.com/markbaaijens/rpmusicserver/issues/131

## Command to detect broken DNS
Do a lookup of your local machine with hardwired dns-server (= local router), filter on error:
* `nslookup $(hostname) $(ip route | grep default | awk '{print $3}') | grep "Can't find"`

**Comment by dartello** [comment]
Lets KISS. In the MachineInfo the IP-address v4 is known. Use this address to link to the available services.

**Comment by dartello** [comment]
Lets KISS. In the MachineInfo the IP-address v4 is known. Use this address to link to the available services.

**Comment by markbaaijens** [comment]
Find ip-address of device: `ip route | grep default  | awk '{print $3}'`
Find gateway (= local router): `ip route | grep default  | awk '{print $3}'`
