### ISSUE TITLE
Cleanup Task-page

### ISSUE THREAD

**Issue by markbaaijens** [markbaaijens/rpmusicserver#199]
As several functions are available in multiple pages, we can cleanup the Task-page

## Use case
As a user, I want a clean interface 

## Tasks
* Tasks, Server => remove Update-button and label CanUpdate
  * is a duplicate of Home/Version, but without all functionality 
* Tasks, Docker => remove Docker-section
  * is a duplicate of Services/Docker, but without information about running containers

## Notes
Removing the Backup-section is taken care of in https://github.com/markbaaijens/rpmusicserver/issues/148

**Comment by NevilleMthw** [comment]
Hi, can I contribute to this issue?

**Comment by NevilleMthw** [comment]
I just realized that your project requires a Linux PC which I do not have unfortunately. I currently work on Windows.

**Comment by NevilleMthw** [comment]
Will definitely take a look. Thanks!
