### ISSUE TITLE
Upgrade from 32-bit to 64-bit OS

### ISSUE THREAD

**Issue by bameije** [markbaaijens/rpmusicserver#303]
Under the latest 32-bit (armhf) OS, some docker-containers will not load b/c 32-bit is no longer supported, moving to 64-bit is the solution for this.

B/c https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2022-01-28/ is the last in line using a zip-archive, we will use this to prevent switching to a different archive mechanism (from zip to xz).

A update/upgrade (which is done automatically in RPMS) will bring the OS to the latest version.

## To do
Describe migation-proces:
* section 'Migrate from version 0.9 to 1.0'
* burn image (use same SD-card)
* run install-script

## Original bug report

Some services not running
Some of the services fail to load. This is a fresh install of the latest version. I followed the install instructions carefully. After a few reboots, I still have the same status:

Services
Status
✔ 22 ssh
✔ 80 rpms/web
✔ 139 samba/netbios
✔ 5000 rpms/api
✗ 8384 syncthing/web
✔ 9002 lms/web
✗ 9091 transmission/web

Docker
✔ lms
✗ transmission
✔ samba
✗ syncthing

Using ssh, I try to list the docker containers, but the transmission and syncthing don't exist:
pi@rpms:~ $ **sudo docker images**
REPOSITORY                         TAG       IMAGE ID       CREATED       SIZE
lmscommunity/logitechmediaserver   stable    4aaea26e79c3   4 weeks ago   168MB
dperson/samba                      latest    d9dda7b56092   2 years ago   53.2MB
pi@rpms:~ $ **sudo docker ps --all**
CONTAINER ID   IMAGE                                     COMMAND                  CREATED          STATUS                    PORTS                                                                                                      NAMES
26502a0ad297   dperson/samba                             "/sbin/tini -- /usr/…"   19 minutes ago   Up 19 minutes (healthy)   0.0.0.0:139->139/tcp, 0.0.0.0:137-138->137-138/udp, 0.0.0.0:445->445/tcp                                   samba
e0d98a3f234c   lmscommunity/logitechmediaserver:stable   "start-container"        19 minutes ago   Up 19 minutes             0.0.0.0:3483->3483/tcp, 0.0.0.0:9002->9002/tcp, 0.0.0.0:9090->9090/tcp, 0.0.0.0:3483->3483/udp, 9000/tcp   lms

**Comment by bameije** [comment]
My system:
* RpModel | Raspberry Pi 3 Model B Rev 1.2 \| 1GB
* OS | Raspbian GNU/Linux 11 (bullseye) \| armv7l 32-bit

Trying to run the container manually:

```
sudo docker run         -d         --rm         --name syncthing         -e PUID=1000         -e PGID=1000         -e TZ=Europe/Amsterdam         -p 8384:8384         -p 22000:22000/tcp         -p 22000:22000/udp         -p 21027:21027/udp         -v /media/usbdata/rpms/config/docker/syncthing:/config         -v /media/usbdata/user/Publiek:/data        lscr.io/linuxserver/syncthing:latest
```

```
Unable to find image 'lscr.io/linuxserver/syncthing:latest' locally
latest: Pulling from linuxserver/syncthing
docker: no matching manifest for linux/arm/v7 in the manifest list entries.
```

So I guess I have another (older) raspi hardware setup than rpms developer?

**Comment by markbaaijens** [comment]
RPMS should not be limited by hardware, be it RP3 or RP4, both are supported and have known installations. Nevertheless, you indicate a problem on RP3.

What does the following command give you:
`sudo docker run \
        -d \
        --rm \
        --name transmission \
        -p 9091:9091 \
        -e PUID=1000 \
        -e PGID=1000 \
        -v /media/usbdata/rpms/config/docker/transmission:/config \
        -v /media/usbdata/user/Publiek/Downloads:/downloads \
        linuxserver/transmission`

**Comment by markbaaijens** [comment]
Probably the problem here is that armhf images were supported during the development of rpms, but they are dropped recently. I'll check further with a vanilla install on a Pi3 to reproduce your case.

**Comment by markbaaijens** [comment]
FYI: right now I'm testing with a 64-bit OS (as a replacement of de currently used 32-bit version of Raspian) on a RP3. All looks well, all the docker-containers (especially transmission and syncthing) are able to load on a clean install to the latest version. After some more testing on my production-system (on a RP4), I'll push the change to the develop-branch. 

This means that if you want to take advantage of this change, you should install from the develop-branch, instructions follow later. Since a long while, it's better to install from the develop-branch b/c the 0.9-version (from the master-branch) is quite aging.

**Comment by markbaaijens** [comment]
Just completed this issue. You might test it to do a re-install by burning a SD-card, place it in your Pi and than run the install-script. Note that this code is not yet in the master-branch, so you have to switch to the develop-branch, see instructions here:
https://github.com/markbaaijens/rpmusicserver#development
